export const sabeMalak = {
  name: "Sabe Malak",
  id: "cb08ee70-d11d-41d4-a766-559c7777a932",
  userId: "d3a4bf12-c171-4494-8ce5-f62540a77369",
  builderVersion: "0.7.5",
  image: "",
  user: "",
  experiencePoints: 900,
  species: {
    name: "Human",
    abilityScoreImprovementSelectedOption: 0,
    abilityScoreImprovement: { Wisdom: 2, Charisma: 1, Strength: 1 },
  },
  classes: [
    {
      name: "Sentinel",
      levels: 3,
      hitPoints: [5, 5],
      abilityScoreImprovements: [],
      archetype: { name: "Path of the Corsair" },
      forcePowers: [
        "Force Push/Pull",
        "Force Disarm",
        "Saber Reflect",
        "Saber Throw",
        "Pyrokinesis",
        "Improved Saber Throw",
        "Improved Pyrokinesis",
        "Force Throw",
        "Saber Ward",
        "Saber Assault",
        "Saber Strike",
      ],
    },
  ],
  baseAbilityScores: {
    Strength: 17,
    Dexterity: 13,
    Constitution: 16,
    Intelligence: 11,
    Wisdom: 16,
    Charisma: 13,
  },
  background: {
    name: "Jedi",
    feat: { name: "Empathic", type: "Feat" },
    feature: "",
  },
  characteristics: {
    alignment: "",
    "Personality Traits": "",
    Ideal: "",
    Bond: "",
    Flaw: "",
    Gender: "",
    "Place of Birth": "",
    Age: "",
    Height: "",
    Weight: "",
    Hair: "",
    Eyes: "",
    Skin: "",
    Appearance: "",
    Backstory: "",
  },
  credits: 0,
  equipment: [
    {
      name: "Martial lightsaber",
      quantity: 1,
      category: "Equipment",
      equipped: true,
    },
    { name: "Weave armor", quantity: 1, category: "Equipment", equipped: true },
    {
      name: "Blaster rifle",
      quantity: 1,
      category: "Equipment",
      equipped: true,
    },
  ],
  currentStats: {
    hitPointsLost: 0,
    temporaryHitPoints: 0,
    techPointsUsed: 0,
    forcePointsUsed: 0,
    superiorityDiceUsed: 0,
    hitDiceUsed: {},
    deathSaves: { successes: 0, failures: 0 },
    hasInspiration: false,
    featuresTimesUsed: {},
    conditions: [],
    exhaustion: 0,
    highLevelCasting: {
      level6: false,
      level7: false,
      level8: false,
      level9: false,
    },
  },
  tweaks: {
    abilityScores: {
      Wisdom: {
        score: { bonus: 1, override: null },
        skills: { Insight: { proficiency: "Proficient" } },
      },
      Charisma: { skills: { Deception: { proficiency: "Proficient" } } },
    },
  },
  customProficiencies: [],
  customLanguages: [],
  customFeatures: [],
  customFeats: [],
  customTechPowers: [],
  customForcePowers: ["Give Life"],
  customEquipment: [],
  settings: {
    isEnforcingForcePrerequisites: true,
    isFixedHitPoints: true,
    abilityScoreMethod: "Manual",
  },
  notes: "",
  createdAt: 1659149840647,
  changedAt: 1670045764660,
  localId: "temp-t6bjjqa8s",
};
